export const countries = [
  { code: 'AF', name: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { code: 'AL', name: 'Albania', cities: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër'] },
  { code: 'DZ', name: 'Algeria', cities: ['Algiers', 'Oran', 'Constantine', 'Annaba'] },
  { code: 'AD', name: 'Andorra', cities: ['Andorra la Vella', 'Escaldes-Engordany'] },
  { code: 'AO', name: 'Angola', cities: ['Luanda', 'Huambo', 'Lobito', 'Benguela'] },
  { code: 'AR', name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza'] },
  { code: 'AM', name: 'Armenia', cities: ['Yerevan', 'Gyumri', 'Vanadzor'] },
  { code: 'AU', name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'] },
  { code: 'AT', name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg'] },
  { code: 'AZ', name: 'Azerbaijan', cities: ['Baku', 'Ganja', 'Sumqayit'] },
  { code: 'BH', name: 'Bahrain', cities: ['Manama', 'Riffa', 'Muharraq'] },
  { code: 'BD', name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi'] },
  { code: 'BB', name: 'Barbados', cities: ['Bridgetown', 'Speightstown'] },
  { code: 'BY', name: 'Belarus', cities: ['Minsk', 'Gomel', 'Mogilev', 'Vitebsk'] },
  { code: 'BE', name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi'] },
  { code: 'BZ', name: 'Belize', cities: ['Belize City', 'Belmopan'] },
  { code: 'BJ', name: 'Benin', cities: ['Cotonou', 'Porto-Novo', 'Parakou'] },
  { code: 'BT', name: 'Bhutan', cities: ['Thimphu', 'Phuntsholing'] },
  { code: 'BO', name: 'Bolivia', cities: ['La Paz', 'Santa Cruz', 'Cochabamba'] },
  { code: 'BA', name: 'Bosnia and Herzegovina', cities: ['Sarajevo', 'Banja Luka', 'Tuzla'] },
  { code: 'BW', name: 'Botswana', cities: ['Gaborone', 'Francistown', 'Molepolole'] },
  { code: 'BR', name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador'] },
  { code: 'BN', name: 'Brunei', cities: ['Bandar Seri Begawan'] },
  { code: 'BG', name: 'Bulgaria', cities: ['Sofia', 'Plovdiv', 'Varna', 'Burgas'] },
  { code: 'BF', name: 'Burkina Faso', cities: ['Ouagadougou', 'Bobo-Dioulasso'] },
  { code: 'BI', name: 'Burundi', cities: ['Bujumbura', 'Gitega'] },
  { code: 'KH', name: 'Cambodia', cities: ['Phnom Penh', 'Siem Reap', 'Battambang'] },
  { code: 'CM', name: 'Cameroon', cities: ['Douala', 'Yaoundé', 'Garoua'] },
  { code: 'CA', name: 'Canada', cities: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Ottawa'] },
  { code: 'CV', name: 'Cape Verde', cities: ['Praia', 'Mindelo'] },
  { code: 'CF', name: 'Central African Republic', cities: ['Bangui'] },
  { code: 'TD', name: 'Chad', cities: ['N\'Djamena', 'Moundou'] },
  { code: 'CL', name: 'Chile', cities: ['Santiago', 'Valparaíso', 'Concepción'] },
  { code: 'CN', name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu'] },
  { code: 'CO', name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla'] },
  { code: 'KM', name: 'Comoros', cities: ['Moroni'] },
  { code: 'CG', name: 'Congo', cities: ['Brazzaville', 'Pointe-Noire'] },
  { code: 'CR', name: 'Costa Rica', cities: ['San José', 'Alajuela', 'Cartago'] },
  { code: 'HR', name: 'Croatia', cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek'] },
  { code: 'CU', name: 'Cuba', cities: ['Havana', 'Santiago de Cuba', 'Camagüey'] },
  { code: 'CY', name: 'Cyprus', cities: ['Nicosia', 'Limassol', 'Larnaca'] },
  { code: 'CZ', name: 'Czech Republic', cities: ['Prague', 'Brno', 'Ostrava', 'Plzeň'] },
  { code: 'DK', name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { code: 'DJ', name: 'Djibouti', cities: ['Djibouti City'] },
  { code: 'DM', name: 'Dominica', cities: ['Roseau'] },
  { code: 'DO', name: 'Dominican Republic', cities: ['Santo Domingo', 'Santiago', 'Puerto Plata'] },
  { code: 'EC', name: 'Ecuador', cities: ['Quito', 'Guayaquil', 'Cuenca'] },
  { code: 'EG', name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Luxor'] },
  { code: 'SV', name: 'El Salvador', cities: ['San Salvador', 'Santa Ana', 'San Miguel'] },
  { code: 'GQ', name: 'Equatorial Guinea', cities: ['Malabo', 'Bata'] },
  { code: 'ER', name: 'Eritrea', cities: ['Asmara'] },
  { code: 'EE', name: 'Estonia', cities: ['Tallinn', 'Tartu', 'Narva'] },
  { code: 'ET', name: 'Ethiopia', cities: ['Addis Ababa', 'Dire Dawa', 'Gondar'] },
  { code: 'FJ', name: 'Fiji', cities: ['Suva', 'Nadi'] },
  { code: 'FI', name: 'Finland', cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa'] },
  { code: 'FR', name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice'] },
  { code: 'GA', name: 'Gabon', cities: ['Libreville', 'Port-Gentil'] },
  { code: 'GM', name: 'Gambia', cities: ['Banjul', 'Serekunda'] },
  { code: 'GE', name: 'Georgia', cities: ['Tbilisi', 'Batumi', 'Kutaisi'] },
  { code: 'DE', name: 'Germany', cities: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt'] },
  { code: 'GH', name: 'Ghana', cities: ['Accra', 'Kumasi', 'Tamale'] },
  { code: 'GR', name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion'] },
  { code: 'GT', name: 'Guatemala', cities: ['Guatemala City', 'Quetzaltenango'] },
  { code: 'GN', name: 'Guinea', cities: ['Conakry'] },
  { code: 'GW', name: 'Guinea-Bissau', cities: ['Bissau'] },
  { code: 'GY', name: 'Guyana', cities: ['Georgetown'] },
  { code: 'HT', name: 'Haiti', cities: ['Port-au-Prince', 'Cap-Haïtien'] },
  { code: 'HN', name: 'Honduras', cities: ['Tegucigalpa', 'San Pedro Sula'] },
  { code: 'HU', name: 'Hungary', cities: ['Budapest', 'Debrecen', 'Szeged', 'Pécs'] },
  { code: 'IS', name: 'Iceland', cities: ['Reykjavik', 'Kópavogur'] },
  { code: 'IN', name: 'India', cities: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Hyderabad'] },
  { code: 'ID', name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan'] },
  { code: 'IR', name: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Shiraz'] },
  { code: 'IQ', name: 'Iraq', cities: ['Baghdad', 'Basra', 'Mosul', 'Erbil'] },
  { code: 'IE', name: 'Ireland', cities: ['Dublin', 'Cork', 'Limerick', 'Galway'] },

  { code: 'IT', name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Florence'] },
  { code: 'JM', name: 'Jamaica', cities: ['Kingston', 'Montego Bay'] },
  { code: 'JP', name: 'Japan', cities: ['Tokyo', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka'] },
  { code: 'JO', name: 'Jordan', cities: ['Amman', 'Zarqa', 'Irbid'] },
  { code: 'KZ', name: 'Kazakhstan', cities: ['Almaty', 'Nur-Sultan', 'Shymkent'] },
  { code: 'KE', name: 'Kenya', cities: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'] },
  { code: 'KW', name: 'Kuwait', cities: ['Kuwait City'] },
  { code: 'KG', name: 'Kyrgyzstan', cities: ['Bishkek', 'Osh'] },
  { code: 'LA', name: 'Laos', cities: ['Vientiane', 'Luang Prabang'] },
  { code: 'LV', name: 'Latvia', cities: ['Riga', 'Daugavpils'] },
  { code: 'LB', name: 'Lebanon', cities: ['Beirut', 'Tripoli', 'Sidon'] },
  { code: 'LR', name: 'Liberia', cities: ['Monrovia'] },
  { code: 'LY', name: 'Libya', cities: ['Tripoli', 'Benghazi', 'Misrata'] },
  { code: 'LI', name: 'Liechtenstein', cities: ['Vaduz'] },
  { code: 'LT', name: 'Lithuania', cities: ['Vilnius', 'Kaunas', 'Klaipėda'] },
  { code: 'LU', name: 'Luxembourg', cities: ['Luxembourg City'] },
  { code: 'MK', name: 'North Macedonia', cities: ['Skopje', 'Bitola'] },
  { code: 'MG', name: 'Madagascar', cities: ['Antananarivo', 'Toamasina'] },
  { code: 'MW', name: 'Malawi', cities: ['Lilongwe', 'Blantyre'] },
  { code: 'MY', name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Johor Bahru'] },
  { code: 'MV', name: 'Maldives', cities: ['Malé'] },
  { code: 'ML', name: 'Mali', cities: ['Bamako'] },
  { code: 'MT', name: 'Malta', cities: ['Valletta', 'Birkirkara'] },
  { code: 'MH', name: 'Marshall Islands', cities: ['Majuro'] },
  { code: 'MR', name: 'Mauritania', cities: ['Nouakchott'] },
  { code: 'MU', name: 'Mauritius', cities: ['Port Louis'] },
  { code: 'MX', name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla'] },
  { code: 'FM', name: 'Micronesia', cities: ['Palikir'] },
  { code: 'MD', name: 'Moldova', cities: ['Chișinău', 'Tiraspol'] },
  { code: 'MC', name: 'Monaco', cities: ['Monaco'] },
  { code: 'MN', name: 'Mongolia', cities: ['Ulaanbaatar', 'Erdenet'] },
  { code: 'ME', name: 'Montenegro', cities: ['Podgorica', 'Nikšić'] },
  { code: 'MA', name: 'Morocco', cities: ['Casablanca', 'Rabat', 'Marrakech', 'Fez'] },
  { code: 'MZ', name: 'Mozambique', cities: ['Maputo', 'Beira', 'Nampula'] },
  { code: 'MM', name: 'Myanmar', cities: ['Yangon', 'Mandalay', 'Naypyidaw'] },
  { code: 'NA', name: 'Namibia', cities: ['Windhoek', 'Walvis Bay'] },
  { code: 'NR', name: 'Nauru', cities: ['Yaren'] },
  { code: 'NP', name: 'Nepal', cities: ['Kathmandu', 'Pokhara', 'Biratnagar'] },
  { code: 'NL', name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht'] },
  { code: 'NZ', name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch'] },
  { code: 'NI', name: 'Nicaragua', cities: ['Managua', 'León'] },
  { code: 'NE', name: 'Niger', cities: ['Niamey'] },
  { code: 'NG', name: 'Nigeria', cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan'] },
  { code: 'NO', name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'] },
  { code: 'OM', name: 'Oman', cities: ['Muscat', 'Salalah'] },
  { code: 'PK', name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad'] },
  { code: 'PW', name: 'Palau', cities: ['Ngerulmud'] },
  { code: 'PA', name: 'Panama', cities: ['Panama City', 'San Miguelito'] },
  { code: 'PG', name: 'Papua New Guinea', cities: ['Port Moresby'] },
  { code: 'PY', name: 'Paraguay', cities: ['Asunción', 'Ciudad del Este'] },
  { code: 'PE', name: 'Peru', cities: ['Lima', 'Arequipa', 'Trujillo'] },
  { code: 'PH', name: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao City', 'Cebu City'] },
  { code: 'PL', name: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'] },
  { code: 'PT', name: 'Portugal', cities: ['Lisbon', 'Porto', 'Braga', 'Coimbra'] },
  { code: 'QA', name: 'Qatar', cities: ['Doha', 'Al Rayyan'] },
  { code: 'RO', name: 'Romania', cities: ['Bucharest', 'Cluj-Napoca', 'Timișoara'] },
  { code: 'RU', name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg'] },
  { code: 'RW', name: 'Rwanda', cities: ['Kigali'] },
  { code: 'SA', name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina'] },
  { code: 'SN', name: 'Senegal', cities: ['Dakar', 'Touba'] },
  { code: 'RS', name: 'Serbia', cities: ['Belgrade', 'Novi Sad', 'Niš'] },
  { code: 'SC', name: 'Seychelles', cities: ['Victoria'] },
  { code: 'SL', name: 'Sierra Leone', cities: ['Freetown'] },
  { code: 'SG', name: 'Singapore', cities: ['Singapore'] },
  { code: 'SK', name: 'Slovakia', cities: ['Bratislava', 'Košice', 'Prešov'] },
  { code: 'SI', name: 'Slovenia', cities: ['Ljubljana', 'Maribor'] },
  { code: 'SB', name: 'Solomon Islands', cities: ['Honiara'] },
  { code: 'SO', name: 'Somalia', cities: ['Mogadishu', 'Hargeisa'] },
  { code: 'ZA', name: 'South Africa', cities: ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria'] },
  { code: 'KR', name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu'] },
  { code: 'SS', name: 'South Sudan', cities: ['Juba'] },
  { code: 'ES', name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza'] },
  { code: 'LK', name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle'] },
  { code: 'SD', name: 'Sudan', cities: ['Khartoum', 'Omdurman'] },
  { code: 'SR', name: 'Suriname', cities: ['Paramaribo'] },
  { code: 'SE', name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala'] },
  { code: 'CH', name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Bern'] },
  { code: 'SY', name: 'Syria', cities: ['Damascus', 'Aleppo', 'Homs'] },
  { code: 'TW', name: 'Taiwan', cities: ['Taipei', 'Kaohsiung', 'Taichung'] },
  { code: 'TJ', name: 'Tajikistan', cities: ['Dushanbe'] },
  { code: 'TZ', name: 'Tanzania', cities: ['Dar es Salaam', 'Dodoma', 'Arusha'] },
  { code: 'TH', name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya'] },
  { code: 'TL', name: 'Timor-Leste', cities: ['Dili'] },
  { code: 'TG', name: 'Togo', cities: ['Lomé'] },
  { code: 'TO', name: 'Tonga', cities: ['Nuku\'alofa'] },
  { code: 'TT', name: 'Trinidad and Tobago', cities: ['Port of Spain', 'San Fernando'] },
  { code: 'TN', name: 'Tunisia', cities: ['Tunis', 'Sfax', 'Sousse'] },
  { code: 'TR', name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'] },
  { code: 'TM', name: 'Turkmenistan', cities: ['Ashgabat'] },
  { code: 'TV', name: 'Tuvalu', cities: ['Funafuti'] },
  { code: 'UG', name: 'Uganda', cities: ['Kampala', 'Gulu'] },
  { code: 'UA', name: 'Ukraine', cities: ['Kyiv', 'Kharkiv', 'Odessa', 'Lviv'] },
  { code: 'AE', name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah'] },
  { code: 'GB', name: 'United Kingdom', cities: ['London', 'Birmingham', 'Manchester', 'Liverpool'] },
  { code: 'US', name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'] },
  { code: 'UY', name: 'Uruguay', cities: ['Montevideo', 'Salto'] },
  { code: 'UZ', name: 'Uzbekistan', cities: ['Tashkent', 'Samarkand', 'Bukhara'] },
  { code: 'VU', name: 'Vanuatu', cities: ['Port Vila'] },
  { code: 'VA', name: 'Vatican City', cities: ['Vatican City'] },
  { code: 'VE', name: 'Venezuela', cities: ['Caracas', 'Maracaibo', 'Valencia'] },
  { code: 'VN', name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang'] },
  { code: 'YE', name: 'Yemen', cities: ['Sana\'a', 'Aden', 'Taiz'] },
  { code: 'ZM', name: 'Zambia', cities: ['Lusaka', 'Kitwe'] },
  { code: 'ZW', name: 'Zimbabwe', cities: ['Harare', 'Bulawayo'] }
];